apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backendService.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.backendService.applicationPort }}
    protocol: TCP
    targetPort: {{ .Values.backendService.applicationPort }}
  selector:
    app: {{ .Values.crossyDeployment.name }}

