apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  YH_MYSQL_PASSWORD: {{ .Values.mysql.auth.rootPassword }}
  YH_MYSQL_HOST: "application-mysql-primary-headless"
