apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ .Values.crossyDeployment.name }}
  name: {{ .Values.crossyDeployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.crossyDeployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.crossyDeployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.crossyDeployment.name }}
    spec:
      containers:
      - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        name: {{ .Values.crossyDeployment.name }}
        ports:
        - containerPort: {{ .Values.crossyDeployment.appContainerPort }}
          protocol: TCP
        env:
        - name: YH_MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.name }}
              key: YH_MYSQL_HOST
        - name: YH_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yhportfoliosecret
              key: mysql-root-password	     
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        resources:
{{  toYaml .Values.resources | indent 10 }}
