apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    name: dockerpull
    creationPolicy: Owner
    type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: yh_portfolio_secret
