apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.clusterSecretName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.awsSecretName }}
  # data:
  # - secretKey: dbrootpass
  #   remoteRef:
  #     key: yhdbrootpassword
