apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    name: yhportfoliosecret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: yh_portfolio_secret
  # data:
  # - secretKey: dbrootpass
  #   remoteRef:
  #     key: yhdbrootpassword
