apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-data
  namespace: logging
data:
  
  curl-script.sh: |
    #!/bin/sh
    
    #Wait for Kibana to be available & healthy
    function wait_for_kibana {
        echo "Testing connection to Kibana"
        until $(curl -k -X GET http://elasticsearch-kibana:5601/); do sleep 5; done
        until [ "$(curl -k -X GET http://elasticsearch-kibana:5601/ | wc -l)" == "0" ]
        do sleep 5
        done
    }
    
    #Import data view
    function import_data_view {
        echo "Importing data_view..."
        OUTPUT=$(curl -k -X POST http://elasticsearch-kibana:5601/api/saved_objects/_import -H "kbn-xsrf: true" --form file=@/kibana/file.ndjson)
        SUCCESS=$(echo ${OUTPUT} | grep -o '"successCount":1' | wc -l)
        if [[ ${SUCCESS} == "1" ]]; then
          printf "\n########## Imported data view successfully! #############################\n"
        else
          printf "\n########## Failure while importing data view #############\n"
        fi
        echo ${OUTPUT}
    }
    
    #Import dashboards
    function import_dashboards {
        echo "Importing dashboards..."
        OUTPUT=$(curl -X POST http://elasticsearch-kibana:5601/api/kibana/dashboards/import?exclude=index-pattern -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d @/kibana/file.json)
        SUCCESS=$(echo ${OUTPUT} | grep -o '"successCount":1' | wc -l)
        if [[ ${SUCCESS} == "1" ]]; then
          printf "\n########## Imported dashboards successfully! #############################\n"
        else
          printf "\n########## Failure while importing dashboards #############\n"
        fi
        echo ${OUTPUT}
    }
    
    wait_for_kibana
    import_data_view
    import_dashboards

  file.ndjson: |
    {"attributes":{"fieldAttrs":"{}","fieldFormatMap":"{}","fields":"[]","name":"yotam-dataview","runtimeFieldMap":"{}","sourceFilters":"[]","timeFieldName":"@timestamp","title":"logstash-yh","typeMeta":"{}"},
    "coreMigrationVersion":"8.6.0","created_at":"2023-02-19T20:33:43.310Z","id":"6ac556f7-8858-454e-8f80-b560e59bdc5f","migrationVersion":{"index-pattern":"8.0.0"},
    "references":[],"type":"index-pattern","updated_at":"2023-02-19T20:33:43.310Z","version":"WzUwLDFd"}
    {"excludedObjects":[],"excludedObjectsCount":0,"exportedCount":1,"missingRefCount":0,"missingReferences":[]}

  file.json: |
    {
      "version": "8.6.0",
      "objects": [
        {
          "id": "ae566280-ad71-11ed-b461-955db46e72a3",
          "type": "dashboard",
          "namespaces": [
            "default"
          ],
          "updated_at": "2023-02-19T20:45:28.616Z",
          "created_at": "2023-02-19T20:45:28.616Z",
          "version": "WzI0OCwxXQ==",
          "attributes": {
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}"
            },
            "timeRestore": false,
            "optionsJSON": "{\"useMargins\":true,\"syncColors\":false,\"syncCursor\":true,\"syncTooltips\":false,\"hidePanelTitles\":false}",
            "description": "",
            "panelsJSON": "[{\"version\":\"8.6.0\",\"type\":\"lens\",\"gridData\":{\"x\":0,\"y\":0,\"w\":24,\"h\":15,\"i\":\"102a9ad6-13da-4afe-a378-11265b65476e\"},\"panelIndex\":\"102a9ad6-13da-4afe-a378-11265b65476e\",\"embeddableConfig\":{\"attributes\":{\"title\":\"\",\"visualizationType\":\"lnsPie\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"6ac556f7-8858-454e-8f80-b560e59bdc5f\",\"name\":\"indexpattern-datasource-layer-3576c048-3836-45b2-88ca-26d4d91a93b0\"}],\"state\":{\"visualization\":{\"shape\":\"donut\",\"layers\":[{\"layerId\":\"3576c048-3836-45b2-88ca-26d4d91a93b0\",\"primaryGroups\":[\"a0557df4-4862-472c-b940-359adca5e7a2\"],\"metrics\":[\"5613b90b-d7f0-4210-9eef-7e6a37d1b814\"],\"numberDisplay\":\"percent\",\"categoryDisplay\":\"default\",\"legendDisplay\":\"default\",\"nestedLegend\":false,\"layerType\":\"data\"}]},\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filters\":[],\"datasourceStates\":{\"formBased\":{\"layers\":{\"3576c048-3836-45b2-88ca-26d4d91a93b0\":{\"columns\":{\"a0557df4-4862-472c-b940-359adca5e7a2\":{\"label\":\"Top 5 values of method.keyword\",\"dataType\":\"string\",\"operationType\":\"terms\",\"scale\":\"ordinal\",\"sourceField\":\"method.keyword\",\"isBucketed\":true,\"params\":{\"size\":5,\"orderBy\":{\"type\":\"column\",\"columnId\":\"5613b90b-d7f0-4210-9eef-7e6a37d1b814\"},\"orderDirection\":\"desc\",\"otherBucket\":true,\"missingBucket\":false,\"parentFormat\":{\"id\":\"terms\"},\"include\":[],\"exclude\":[],\"includeIsRegex\":false,\"excludeIsRegex\":false}},\"5613b90b-d7f0-4210-9eef-7e6a37d1b814\":{\"label\":\"Count of records\",\"dataType\":\"number\",\"operationType\":\"count\",\"isBucketed\":false,\"scale\":\"ratio\",\"sourceField\":\"___records___\",\"params\":{\"emptyAsNull\":true}}},\"columnOrder\":[\"a0557df4-4862-472c-b940-359adca5e7a2\",\"5613b90b-d7f0-4210-9eef-7e6a37d1b814\"],\"incompleteColumns\":{},\"sampling\":1}}},\"textBased\":{\"layers\":{}}},\"internalReferences\":[],\"adHocDataViews\":{}}},\"hidePanelTitles\":false,\"enhancements\":{}},\"title\":\"methods\"},{\"version\":\"8.6.0\",\"type\":\"lens\",\"gridData\":{\"x\":24,\"y\":0,\"w\":24,\"h\":15,\"i\":\"37d708b4-eca8-480e-a305-2956a946580f\"},\"panelIndex\":\"37d708b4-eca8-480e-a305-2956a946580f\",\"embeddableConfig\":{\"attributes\":{\"title\":\"\",\"visualizationType\":\"lnsPie\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"6ac556f7-8858-454e-8f80-b560e59bdc5f\",\"name\":\"indexpattern-datasource-layer-d4027788-d9d6-4a15-b616-bcb5a0e48a07\"}],\"state\":{\"visualization\":{\"shape\":\"pie\",\"layers\":[{\"layerId\":\"d4027788-d9d6-4a15-b616-bcb5a0e48a07\",\"primaryGroups\":[\"f9764d1a-a5c7-430c-afe7-6f9f64744673\"],\"metrics\":[\"abf986ee-2ae6-48f7-aa8e-b202216408ea\"],\"numberDisplay\":\"percent\",\"categoryDisplay\":\"default\",\"legendDisplay\":\"default\",\"nestedLegend\":false,\"layerType\":\"data\"}]},\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filters\":[],\"datasourceStates\":{\"formBased\":{\"layers\":{\"d4027788-d9d6-4a15-b616-bcb5a0e48a07\":{\"columns\":{\"f9764d1a-a5c7-430c-afe7-6f9f64744673\":{\"label\":\"Top 5 values of request.keyword\",\"dataType\":\"string\",\"operationType\":\"terms\",\"scale\":\"ordinal\",\"sourceField\":\"request.keyword\",\"isBucketed\":true,\"params\":{\"size\":5,\"orderBy\":{\"type\":\"column\",\"columnId\":\"abf986ee-2ae6-48f7-aa8e-b202216408ea\"},\"orderDirection\":\"desc\",\"otherBucket\":true,\"missingBucket\":false,\"parentFormat\":{\"id\":\"terms\"},\"include\":[],\"exclude\":[],\"includeIsRegex\":false,\"excludeIsRegex\":false}},\"abf986ee-2ae6-48f7-aa8e-b202216408ea\":{\"label\":\"Count of records\",\"dataType\":\"number\",\"operationType\":\"count\",\"isBucketed\":false,\"scale\":\"ratio\",\"sourceField\":\"___records___\",\"params\":{\"emptyAsNull\":true}}},\"columnOrder\":[\"f9764d1a-a5c7-430c-afe7-6f9f64744673\",\"abf986ee-2ae6-48f7-aa8e-b202216408ea\"],\"incompleteColumns\":{},\"sampling\":1}}},\"textBased\":{\"layers\":{}}},\"internalReferences\":[],\"adHocDataViews\":{}}},\"enhancements\":{}}}]",
            "title": "yotam portfolio",
            "version": 1
          },
          "references": [
            {
              "type": "index-pattern",
              "id": "6ac556f7-8858-454e-8f80-b560e59bdc5f",
              "name": "102a9ad6-13da-4afe-a378-11265b65476e:indexpattern-datasource-layer-3576c048-3836-45b2-88ca-26d4d91a93b0"
            },
            {
              "type": "index-pattern",
              "id": "6ac556f7-8858-454e-8f80-b560e59bdc5f",
              "name": "37d708b4-eca8-480e-a305-2956a946580f:indexpattern-datasource-layer-d4027788-d9d6-4a15-b616-bcb5a0e48a07"
            }
          ],
          "migrationVersion": {
            "dashboard": "8.6.0"
          },
          "coreMigrationVersion": "8.6.0"
        },
        {
          "id": "6ac556f7-8858-454e-8f80-b560e59bdc5f",
          "type": "index-pattern",
          "namespaces": [
            "default"
          ],
          "updated_at": "2023-02-19T20:33:43.310Z",
          "created_at": "2023-02-19T20:33:43.310Z",
          "version": "WzUwLDFd",
          "attributes": {
            "fieldAttrs": "{}",
            "title": "logstash-yh",
            "timeFieldName": "@timestamp",
            "sourceFilters": "[]",
            "fields": "[]",
            "fieldFormatMap": "{}",
            "typeMeta": "{}",
            "runtimeFieldMap": "{}",
            "name": "yotam-dataview"
          },
          "references": [],
          "migrationVersion": {
            "index-pattern": "8.0.0"
          },
          "coreMigrationVersion": "8.6.0"
        }
      ]
    }