apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-data
  namespace: logging
data:
  
  curl-script.sh: |
    #!/bin/sh
    
    #Wait for Kibana to be available & healthy
    function wait_for_kibana {
        echo "Testing connection to Kibana"
        until $(curl -k -X GET http://elasticsearch-kibana:5601/); do sleep 5; done
        until [ "$(curl -k -X GET http://elasticsearch-kibana:5601/ | wc -l)" == "0" ]
        do sleep 5
        done
    }
    
    #Import data view
    function import_data_view {
        echo "Importing data_view..."
        OUTPUT=$(curl -k -X POST http://elasticsearch-kibana:5601/api/saved_objects/_import -H "kbn-xsrf: true" --form file=@/kibana/file.ndjson)
        SUCCESS=$(echo ${OUTPUT} | grep -o '"successCount":1' | wc -l)
        if [[ ${SUCCESS} == "1" ]]; then
          printf "\n########## Imported data view successfully! #############################\n"
        else
          printf "\n########## Failure while importing data view #############\n"
        fi
        echo ${OUTPUT}
    }
    
    #Import dashboards
    function import_dashboards {
        echo "Importing dashboards..."
        OUTPUT=$(curl -X POST http://elasticsearch-kibana:5601/api/kibana/dashboards/import?exclude=index-pattern -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d @/kibana/file.json)
        SUCCESS=$(echo ${OUTPUT} | grep -o '"successCount":1' | wc -l)
        if [[ ${SUCCESS} == "1" ]]; then
          printf "\n########## Imported dashboards successfully! #############################\n"
        else
          printf "\n########## Failure while importing dashboards #############\n"
        fi
        echo ${OUTPUT}
    }
    
    wait_for_kibana
    import_data_view
    import_dashboards

  file.ndjson: |
    {"attributes":{"fieldAttrs":"{}","fieldFormatMap":"{}","fields":"[]","name":"yh-dataview","runtimeFieldMap":"{}","sourceFilters":"[]","timeFieldName":"@timestamp","title":"logstash-yh","typeMeta":"{}"},"coreMigrationVersion":"8.6.0","created_at":"2023-02-19T13:00:30.025Z","id":"cc8c970d-3294-430e-8371-5d4824d3fb0f","migrationVersion":{"index-pattern":"8.0.0"},"references":[],"type":"index-pattern","updated_at":"2023-02-19T13:00:30.025Z","version":"WzE1MiwxXQ=="}
    {"excludedObjects":[],"excludedObjectsCount":0,"exportedCount":1,"missingRefCount":0,"missingReferences":[]}

  file.json: |
    {
      "version": "8.6.0",
      "objects": [
        {
          "id": "1055fc20-b056-11ed-92bc-cbaa8e7bbf18",
          "type": "dashboard",
          "namespaces": [
            "default"
          ],
          "updated_at": "2023-02-19T13:05:20.610Z",
          "created_at": "2023-02-19T13:05:20.610Z",
          "version": "WzMwOSwxXQ==",
          "attributes": {
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}"
            },
            "timeRestore": false,
            "optionsJSON": "{\"useMargins\":true,\"syncColors\":false,\"syncCursor\":true,\"syncTooltips\":false,\"hidePanelTitles\":false}",
            "description": "",
            "panelsJSON": "[{\"version\":\"8.6.0\",\"type\":\"lens\",\"gridData\":{\"x\":0,\"y\":0,\"w\":24,\"h\":15,\"i\":\"4866bb72-d45a-40b9-a0b5-d8d8e7f5bd99\"},\"panelIndex\":\"4866bb72-d45a-40b9-a0b5-d8d8e7f5bd99\",\"embeddableConfig\":{\"attributes\":{\"title\":\"\",\"visualizationType\":\"lnsPie\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"cc8c970d-3294-430e-8371-5d4824d3fb0f\",\"name\":\"indexpattern-datasource-layer-47805287-60bb-4dab-84e9-49f395674cc6\"}],\"state\":{\"visualization\":{\"shape\":\"donut\",\"layers\":[{\"layerId\":\"47805287-60bb-4dab-84e9-49f395674cc6\",\"primaryGroups\":[\"ecd7e88f-10fe-4459-b9a2-5d0f641f77ab\"],\"metrics\":[\"4c4f7555-96ff-4e54-acdf-1c823714911a\"],\"numberDisplay\":\"percent\",\"categoryDisplay\":\"default\",\"legendDisplay\":\"default\",\"nestedLegend\":false,\"layerType\":\"data\"}]},\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filters\":[],\"datasourceStates\":{\"formBased\":{\"layers\":{\"47805287-60bb-4dab-84e9-49f395674cc6\":{\"columns\":{\"ecd7e88f-10fe-4459-b9a2-5d0f641f77ab\":{\"label\":\"Top 5 values of method.keyword\",\"dataType\":\"string\",\"operationType\":\"terms\",\"scale\":\"ordinal\",\"sourceField\":\"method.keyword\",\"isBucketed\":true,\"params\":{\"size\":5,\"orderBy\":{\"type\":\"column\",\"columnId\":\"4c4f7555-96ff-4e54-acdf-1c823714911a\"},\"orderDirection\":\"desc\",\"otherBucket\":true,\"missingBucket\":false,\"parentFormat\":{\"id\":\"terms\"},\"include\":[],\"exclude\":[],\"includeIsRegex\":false,\"excludeIsRegex\":false}},\"4c4f7555-96ff-4e54-acdf-1c823714911a\":{\"label\":\"Count of records\",\"dataType\":\"number\",\"operationType\":\"count\",\"isBucketed\":false,\"scale\":\"ratio\",\"sourceField\":\"___records___\",\"params\":{\"emptyAsNull\":true}}},\"columnOrder\":[\"ecd7e88f-10fe-4459-b9a2-5d0f641f77ab\",\"4c4f7555-96ff-4e54-acdf-1c823714911a\"],\"incompleteColumns\":{},\"sampling\":1}}},\"textBased\":{\"layers\":{}}},\"internalReferences\":[],\"adHocDataViews\":{}}},\"hidePanelTitles\":false,\"enhancements\":{}},\"title\":\"methods\"},{\"version\":\"8.6.0\",\"type\":\"lens\",\"gridData\":{\"x\":24,\"y\":0,\"w\":24,\"h\":15,\"i\":\"5d2d1a8b-408d-4043-921d-4159f593ad5e\"},\"panelIndex\":\"5d2d1a8b-408d-4043-921d-4159f593ad5e\",\"embeddableConfig\":{\"attributes\":{\"title\":\"\",\"visualizationType\":\"lnsXY\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"cc8c970d-3294-430e-8371-5d4824d3fb0f\",\"name\":\"indexpattern-datasource-layer-c9083d69-02e0-4ea0-a1d0-d253f0a64667\"}],\"state\":{\"visualization\":{\"legend\":{\"isVisible\":true,\"position\":\"right\"},\"valueLabels\":\"hide\",\"fittingFunction\":\"None\",\"axisTitlesVisibilitySettings\":{\"x\":true,\"yLeft\":true,\"yRight\":true},\"tickLabelsVisibilitySettings\":{\"x\":true,\"yLeft\":true,\"yRight\":true},\"labelsOrientation\":{\"x\":0,\"yLeft\":0,\"yRight\":0},\"gridlinesVisibilitySettings\":{\"x\":true,\"yLeft\":true,\"yRight\":true},\"preferredSeriesType\":\"bar_stacked\",\"layers\":[{\"layerId\":\"c9083d69-02e0-4ea0-a1d0-d253f0a64667\",\"accessors\":[\"3a946b21-2d84-4069-aa25-e61d6f34e5c7\"],\"position\":\"top\",\"seriesType\":\"bar_stacked\",\"showGridlines\":false,\"layerType\":\"data\",\"xAccessor\":\"484eb55a-4ff8-4f0e-bfd4-6040d27d7195\"}]},\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filters\":[],\"datasourceStates\":{\"formBased\":{\"layers\":{\"c9083d69-02e0-4ea0-a1d0-d253f0a64667\":{\"columns\":{\"484eb55a-4ff8-4f0e-bfd4-6040d27d7195\":{\"label\":\"Top 5 values of request.keyword\",\"dataType\":\"string\",\"operationType\":\"terms\",\"scale\":\"ordinal\",\"sourceField\":\"request.keyword\",\"isBucketed\":true,\"params\":{\"size\":5,\"orderBy\":{\"type\":\"column\",\"columnId\":\"3a946b21-2d84-4069-aa25-e61d6f34e5c7\"},\"orderDirection\":\"desc\",\"otherBucket\":true,\"missingBucket\":false,\"parentFormat\":{\"id\":\"terms\"},\"include\":[],\"exclude\":[],\"includeIsRegex\":false,\"excludeIsRegex\":false}},\"3a946b21-2d84-4069-aa25-e61d6f34e5c7\":{\"label\":\"Count of records\",\"dataType\":\"number\",\"operationType\":\"count\",\"isBucketed\":false,\"scale\":\"ratio\",\"sourceField\":\"___records___\",\"params\":{\"emptyAsNull\":true}}},\"columnOrder\":[\"484eb55a-4ff8-4f0e-bfd4-6040d27d7195\",\"3a946b21-2d84-4069-aa25-e61d6f34e5c7\"],\"incompleteColumns\":{},\"sampling\":1}}},\"textBased\":{\"layers\":{}}},\"internalReferences\":[],\"adHocDataViews\":{}}},\"hidePanelTitles\":false,\"enhancements\":{}},\"title\":\"requests\"}]",
            "title": "yh-dashboard",
            "version": 1
          },
          "references": [
            {
              "type": "index-pattern",
              "id": "cc8c970d-3294-430e-8371-5d4824d3fb0f",
              "name": "4866bb72-d45a-40b9-a0b5-d8d8e7f5bd99:indexpattern-datasource-layer-47805287-60bb-4dab-84e9-49f395674cc6"
            },
            {
              "type": "index-pattern",
              "id": "cc8c970d-3294-430e-8371-5d4824d3fb0f",
              "name": "5d2d1a8b-408d-4043-921d-4159f593ad5e:indexpattern-datasource-layer-c9083d69-02e0-4ea0-a1d0-d253f0a64667"
            }
          ],
          "migrationVersion": {
            "dashboard": "8.6.0"
          },
          "coreMigrationVersion": "8.6.0"
        },
        {
          "id": "cc8c970d-3294-430e-8371-5d4824d3fb0f",
          "type": "index-pattern",
          "namespaces": [
            "default"
          ],
          "updated_at": "2023-02-19T13:00:30.025Z",
          "created_at": "2023-02-19T13:00:30.025Z",
          "version": "WzE1MiwxXQ==",
          "attributes": {
            "fieldAttrs": "{}",
            "title": "logstash-yh",
            "timeFieldName": "@timestamp",
            "sourceFilters": "[]",
            "fields": "[]",
            "fieldFormatMap": "{}",
            "typeMeta": "{}",
            "runtimeFieldMap": "{}",
            "name": "yh-dataview"
          },
          "references": [],
          "migrationVersion": {
            "index-pattern": "8.0.0"
          },
          "coreMigrationVersion": "8.6.0"
        }
      ]
    }