apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      
      ### NO NEED OF AUTHENTICATION BECAUSE OF CLUSTER IAM ROLE
      # auth:
      #   secretRef:
      #     accessKeyIDSecretRef:
      #       name: ""
      #       key: access-key
      #     secretAccessKeySecretRef:
      #       name: awssm-secret
      #       key: secret-access-key
