apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    aws:
      service: {{ .Values.secretStore.awsSrevice }}
      region: {{ .Values.secretStore.region }}
      
      ### NO NEED OF AUTHENTICATION BECAUSE OF CLUSTER IAM ROLE
      # auth:
      #   secretRef:
      #     accessKeyIDSecretRef:
      #       name: ""
      #       key: access-key
      #     secretAccessKeySecretRef:
      #       name: awssm-secret
      #       key: secret-access-key
