{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.tls.clusterissuer.name }}
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory  # for staging
    # server: https://acme-v02.api.letsencrypt.org/directory # for production

    email: yotam@email.com
    privateKeySecretRef:
      name: letsencrypt-issuer-key
    # solvers:
    # - http01:
    #    ingress:
    #      class: {{ .Values.ingress.className }}
    solvers:
    - dns01:
        route53:
          region: eu-west-2
          hostedZoneID: Z03492862PT1PY19EQIFA
          role: arn:aws:iam::644435390668:role/yh-eks-node-group
      selector:
        dnsZones:
          - "yotam.store"
{{- end }}
