{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.tls.clusterissuer.name }}
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: yotam@email.com
    privateKeySecretRef:
      name: letsencrypt-issuer-key
    solvers:
    - http01:
       ingress:
         class: {{ .Values.ingress.className }}
{{- end }}