apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    name: try
    creationPolicy: Owner
  data:
  - secretKey: yhdbrootpassword
    remoteRef:
      key: dbrootpass
      version: provider-key-version
      property: provider-key-property
  dataFrom:
  - extract:
      key: dbrootpass

# apiVersion: "kubernetes-client.io/v1"
# kind: ExternalSecret
# metadata:
#   name: test-db-secret
# spec:
#   backendType: secretsManager
#   data:
#     - key: dev/database
#       name: DB_CREDENTIALS