{
 "title": "yotam portfolio",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "number of pods for namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (namespace)(sum by (namespace,pod,container)(kube_pod_container_info{container!=\"\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"cpu\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU of crossyroad containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total { container=\"crossyroad\" } [5m] )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "number of available nodes",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU for node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum by (node)(rate(node_cpu_seconds_total{mode!=\"idle\"}[2m]))*100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}