# apiVersion: v1
# kind: Namespace
# metadata:
#   name: application
#   labels:
#     name: application

# ---

apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    name: security

---

apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring

