apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: git@github.com:yotam-halperin/portfolio-charts.git
    targetRevision: HEAD
    path: logging/fluentd
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
    - CreateNamespace=False
    automated:
      prune: true
      selfHeal: true


      