apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: init
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:yotam-halperin/portfolio-charts.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=False
    automated:
      prune: true
      selfHeal: true


      